[2023-07-20T12:52:42.675+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_data_processing.run_spark scheduled__2023-07-02T08:00:00+00:00 [queued]>
[2023-07-20T12:52:42.681+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_data_processing.run_spark scheduled__2023-07-02T08:00:00+00:00 [queued]>
[2023-07-20T12:52:42.681+0530] {taskinstance.py:1308} INFO - Starting attempt 20 of 22
[2023-07-20T12:52:42.711+0530] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_spark> on 2023-07-02 08:00:00+00:00
[2023-07-20T12:52:42.715+0530] {standard_task_runner.py:57} INFO - Started process 82053 to run task
[2023-07-20T12:52:42.721+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'spark_data_processing', 'run_spark', 'scheduled__2023-07-02T08:00:00+00:00', '--job-id', '417', '--raw', '--subdir', 'DAGS_FOLDER/assignment2.py', '--cfg-path', '/tmp/tmp5jxdd6ic']
[2023-07-20T12:52:42.722+0530] {standard_task_runner.py:85} INFO - Job 417: Subtask run_spark
[2023-07-20T12:52:42.792+0530] {task_command.py:410} INFO - Running <TaskInstance: spark_data_processing.run_spark scheduled__2023-07-02T08:00:00+00:00 [running]> on host neosoft-Latitude-E5270
[2023-07-20T12:52:42.859+0530] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='nikitaneti21@gmail.com' AIRFLOW_CTX_DAG_OWNER='Nikita' AIRFLOW_CTX_DAG_ID='spark_data_processing' AIRFLOW_CTX_TASK_ID='run_spark' AIRFLOW_CTX_EXECUTION_DATE='2023-07-02T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='20' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-02T08:00:00+00:00'
[2023-07-20T12:52:42.861+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-20T12:52:42.862+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\nspark-submit --master local /home/neosoft/airflow/Assignment_airflow/pyspark1.py']
[2023-07-20T12:52:42.869+0530] {subprocess.py:86} INFO - Output:
[2023-07-20T12:52:45.584+0530] {subprocess.py:93} INFO - 23/07/20 12:52:45 WARN Utils: Your hostname, neosoft-Latitude-E5270 resolves to a loopback address: 127.0.1.1; using 10.0.28.108 instead (on interface enp0s31f6)
[2023-07-20T12:52:45.587+0530] {subprocess.py:93} INFO - 23/07/20 12:52:45 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2023-07-20T12:52:46.930+0530] {subprocess.py:93} INFO - 23/07/20 12:52:46 INFO SparkContext: Running Spark version 3.4.0
[2023-07-20T12:52:47.063+0530] {subprocess.py:93} INFO - 23/07/20 12:52:47 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2023-07-20T12:52:47.238+0530] {subprocess.py:93} INFO - 23/07/20 12:52:47 INFO ResourceUtils: ==============================================================
[2023-07-20T12:52:47.239+0530] {subprocess.py:93} INFO - 23/07/20 12:52:47 INFO ResourceUtils: No custom resources configured for spark.driver.
[2023-07-20T12:52:47.240+0530] {subprocess.py:93} INFO - 23/07/20 12:52:47 INFO ResourceUtils: ==============================================================
[2023-07-20T12:52:47.241+0530] {subprocess.py:93} INFO - 23/07/20 12:52:47 INFO SparkContext: Submitted application: pyspark1.py
[2023-07-20T12:52:47.278+0530] {subprocess.py:93} INFO - 23/07/20 12:52:47 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2023-07-20T12:52:47.298+0530] {subprocess.py:93} INFO - 23/07/20 12:52:47 INFO ResourceProfile: Limiting resource is cpu
[2023-07-20T12:52:47.300+0530] {subprocess.py:93} INFO - 23/07/20 12:52:47 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2023-07-20T12:52:47.384+0530] {subprocess.py:93} INFO - 23/07/20 12:52:47 INFO SecurityManager: Changing view acls to: neosoft
[2023-07-20T12:52:47.385+0530] {subprocess.py:93} INFO - 23/07/20 12:52:47 INFO SecurityManager: Changing modify acls to: neosoft
[2023-07-20T12:52:47.386+0530] {subprocess.py:93} INFO - 23/07/20 12:52:47 INFO SecurityManager: Changing view acls groups to:
[2023-07-20T12:52:47.387+0530] {subprocess.py:93} INFO - 23/07/20 12:52:47 INFO SecurityManager: Changing modify acls groups to:
[2023-07-20T12:52:47.387+0530] {subprocess.py:93} INFO - 23/07/20 12:52:47 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: neosoft; groups with view permissions: EMPTY; users with modify permissions: neosoft; groups with modify permissions: EMPTY
[2023-07-20T12:52:47.777+0530] {subprocess.py:93} INFO - 23/07/20 12:52:47 INFO Utils: Successfully started service 'sparkDriver' on port 44529.
[2023-07-20T12:52:47.826+0530] {subprocess.py:93} INFO - 23/07/20 12:52:47 INFO SparkEnv: Registering MapOutputTracker
[2023-07-20T12:52:47.865+0530] {subprocess.py:93} INFO - 23/07/20 12:52:47 INFO SparkEnv: Registering BlockManagerMaster
[2023-07-20T12:52:47.888+0530] {subprocess.py:93} INFO - 23/07/20 12:52:47 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2023-07-20T12:52:47.889+0530] {subprocess.py:93} INFO - 23/07/20 12:52:47 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2023-07-20T12:52:47.893+0530] {subprocess.py:93} INFO - 23/07/20 12:52:47 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2023-07-20T12:52:47.921+0530] {subprocess.py:93} INFO - 23/07/20 12:52:47 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-dfd751ac-05b9-412f-a736-c661e58c3880
[2023-07-20T12:52:48.018+0530] {subprocess.py:93} INFO - 23/07/20 12:52:48 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2023-07-20T12:52:48.046+0530] {subprocess.py:93} INFO - 23/07/20 12:52:48 INFO SparkEnv: Registering OutputCommitCoordinator
[2023-07-20T12:52:48.216+0530] {subprocess.py:93} INFO - 23/07/20 12:52:48 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2023-07-20T12:52:48.285+0530] {subprocess.py:93} INFO - 23/07/20 12:52:48 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2023-07-20T12:52:48.444+0530] {subprocess.py:93} INFO - 23/07/20 12:52:48 INFO Executor: Starting executor ID driver on host 10.0.28.108
[2023-07-20T12:52:48.456+0530] {subprocess.py:93} INFO - 23/07/20 12:52:48 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2023-07-20T12:52:48.480+0530] {subprocess.py:93} INFO - 23/07/20 12:52:48 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 40859.
[2023-07-20T12:52:48.480+0530] {subprocess.py:93} INFO - 23/07/20 12:52:48 INFO NettyBlockTransferService: Server created on 10.0.28.108:40859
[2023-07-20T12:52:48.482+0530] {subprocess.py:93} INFO - 23/07/20 12:52:48 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2023-07-20T12:52:48.489+0530] {subprocess.py:93} INFO - 23/07/20 12:52:48 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 10.0.28.108, 40859, None)
[2023-07-20T12:52:48.494+0530] {subprocess.py:93} INFO - 23/07/20 12:52:48 INFO BlockManagerMasterEndpoint: Registering block manager 10.0.28.108:40859 with 434.4 MiB RAM, BlockManagerId(driver, 10.0.28.108, 40859, None)
[2023-07-20T12:52:48.497+0530] {subprocess.py:93} INFO - 23/07/20 12:52:48 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 10.0.28.108, 40859, None)
[2023-07-20T12:52:48.498+0530] {subprocess.py:93} INFO - 23/07/20 12:52:48 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 10.0.28.108, 40859, None)
[2023-07-20T12:52:49.162+0530] {subprocess.py:93} INFO - 23/07/20 12:52:49 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2023-07-20T12:52:49.169+0530] {subprocess.py:93} INFO - 23/07/20 12:52:49 INFO SharedState: Warehouse path is 'file:/tmp/airflowtmpf9tivn4y/spark-warehouse'.
[2023-07-20T12:52:50.667+0530] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-07-20T12:52:50.668+0530] {subprocess.py:93} INFO -   File "/home/neosoft/airflow/Assignment_airflow/pyspark1.py", line 19, in <module>
[2023-07-20T12:52:50.668+0530] {subprocess.py:93} INFO -     df = spark.read.jdbc(jdbc_url, table_name, properties=properties)
[2023-07-20T12:52:50.668+0530] {subprocess.py:93} INFO -   File "/opt/spark/spark-3.4.0-bin-hadoop3/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 927, in jdbc
[2023-07-20T12:52:50.668+0530] {subprocess.py:93} INFO -   File "/opt/spark/spark-3.4.0-bin-hadoop3/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2023-07-20T12:52:50.668+0530] {subprocess.py:93} INFO -   File "/opt/spark/spark-3.4.0-bin-hadoop3/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 169, in deco
[2023-07-20T12:52:50.668+0530] {subprocess.py:93} INFO -   File "/opt/spark/spark-3.4.0-bin-hadoop3/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2023-07-20T12:52:50.669+0530] {subprocess.py:93} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o25.jdbc.
[2023-07-20T12:52:50.669+0530] {subprocess.py:93} INFO - : java.lang.ClassNotFoundException: com.mysql.cj.jdbc.Driver
[2023-07-20T12:52:50.669+0530] {subprocess.py:93} INFO - 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
[2023-07-20T12:52:50.669+0530] {subprocess.py:93} INFO - 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
[2023-07-20T12:52:50.669+0530] {subprocess.py:93} INFO - 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[2023-07-20T12:52:50.669+0530] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.DriverRegistry$.register(DriverRegistry.scala:46)
[2023-07-20T12:52:50.670+0530] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.$anonfun$driverClass$1(JDBCOptions.scala:103)
[2023-07-20T12:52:50.670+0530] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.$anonfun$driverClass$1$adapted(JDBCOptions.scala:103)
[2023-07-20T12:52:50.670+0530] {subprocess.py:93} INFO - 	at scala.Option.foreach(Option.scala:407)
[2023-07-20T12:52:50.670+0530] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:103)
[2023-07-20T12:52:50.670+0530] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:41)
[2023-07-20T12:52:50.670+0530] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:34)
[2023-07-20T12:52:50.670+0530] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:346)
[2023-07-20T12:52:50.670+0530] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:229)
[2023-07-20T12:52:50.671+0530] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:211)
[2023-07-20T12:52:50.671+0530] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2023-07-20T12:52:50.671+0530] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
[2023-07-20T12:52:50.671+0530] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:172)
[2023-07-20T12:52:50.671+0530] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.jdbc(DataFrameReader.scala:249)
[2023-07-20T12:52:50.671+0530] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-07-20T12:52:50.671+0530] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-07-20T12:52:50.671+0530] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-07-20T12:52:50.672+0530] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2023-07-20T12:52:50.672+0530] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2023-07-20T12:52:50.672+0530] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2023-07-20T12:52:50.672+0530] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2023-07-20T12:52:50.672+0530] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2023-07-20T12:52:50.672+0530] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2023-07-20T12:52:50.672+0530] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2023-07-20T12:52:50.672+0530] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2023-07-20T12:52:50.673+0530] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2023-07-20T12:52:50.673+0530] {subprocess.py:93} INFO - 
[2023-07-20T12:52:50.711+0530] {subprocess.py:93} INFO - 23/07/20 12:52:50 INFO SparkContext: Invoking stop() from shutdown hook
[2023-07-20T12:52:50.712+0530] {subprocess.py:93} INFO - 23/07/20 12:52:50 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2023-07-20T12:52:50.726+0530] {subprocess.py:93} INFO - 23/07/20 12:52:50 INFO SparkUI: Stopped Spark web UI at http://10.0.28.108:4040
[2023-07-20T12:52:50.743+0530] {subprocess.py:93} INFO - 23/07/20 12:52:50 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2023-07-20T12:52:50.757+0530] {subprocess.py:93} INFO - 23/07/20 12:52:50 INFO MemoryStore: MemoryStore cleared
[2023-07-20T12:52:50.757+0530] {subprocess.py:93} INFO - 23/07/20 12:52:50 INFO BlockManager: BlockManager stopped
[2023-07-20T12:52:50.765+0530] {subprocess.py:93} INFO - 23/07/20 12:52:50 INFO BlockManagerMaster: BlockManagerMaster stopped
[2023-07-20T12:52:50.770+0530] {subprocess.py:93} INFO - 23/07/20 12:52:50 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2023-07-20T12:52:50.775+0530] {subprocess.py:93} INFO - 23/07/20 12:52:50 INFO SparkContext: Successfully stopped SparkContext
[2023-07-20T12:52:50.776+0530] {subprocess.py:93} INFO - 23/07/20 12:52:50 INFO ShutdownHookManager: Shutdown hook called
[2023-07-20T12:52:50.777+0530] {subprocess.py:93} INFO - 23/07/20 12:52:50 INFO ShutdownHookManager: Deleting directory /tmp/spark-eacb2ea4-8590-4264-a0d7-29e1ee9a4291
[2023-07-20T12:52:50.779+0530] {subprocess.py:93} INFO - 23/07/20 12:52:50 INFO ShutdownHookManager: Deleting directory /tmp/spark-eacb2ea4-8590-4264-a0d7-29e1ee9a4291/pyspark-d04ea01e-cf28-4f27-be0d-1951d68041d1
[2023-07-20T12:52:50.782+0530] {subprocess.py:93} INFO - 23/07/20 12:52:50 INFO ShutdownHookManager: Deleting directory /tmp/spark-56f5c60b-2e39-42a4-9c42-403e9f8724c4
[2023-07-20T12:52:50.823+0530] {subprocess.py:97} INFO - Command exited with return code 1
[2023-07-20T12:52:50.831+0530] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/neosoft/airflow/py_env/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-07-20T12:52:50.834+0530] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_data_processing, task_id=run_spark, execution_date=20230702T080000, start_date=20230720T072242, end_date=20230720T072250
[2023-07-20T12:52:50.847+0530] {base.py:73} INFO - Using connection ID 'smtp_default' for task execution.
[2023-07-20T12:52:50.847+0530] {email.py:268} INFO - Email alerting: attempt 1
[2023-07-20T12:52:52.728+0530] {base.py:73} INFO - Using connection ID 'smtp_default' for task execution.
[2023-07-20T12:52:52.729+0530] {email.py:268} INFO - Email alerting: attempt 1
[2023-07-20T12:52:54.582+0530] {taskinstance.py:1889} ERROR - Failed to send email to: ['nikitaneti21@gmail.com']
Traceback (most recent call last):
  File "/home/neosoft/airflow/py_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/neosoft/airflow/py_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1558, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/neosoft/airflow/py_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1628, in _execute_task
    result = execute_callable(context=context)
  File "/home/neosoft/airflow/py_env/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neosoft/airflow/py_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2295, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/neosoft/airflow/py_env/lib/python3.8/site-packages/airflow/utils/email.py", line 78, in send_email
    return backend(
  File "/home/neosoft/airflow/py_env/lib/python3.8/site-packages/airflow/utils/email.py", line 152, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/neosoft/airflow/py_env/lib/python3.8/site-packages/airflow/utils/email.py", line 279, in send_mime_email
    smtp_conn.login(smtp_user, smtp_password)
  File "/usr/lib/python3.8/smtplib.py", line 743, in login
    raise last_exception
  File "/usr/lib/python3.8/smtplib.py", line 732, in login
    (code, resp) = self.auth(
  File "/usr/lib/python3.8/smtplib.py", line 655, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (534, b'5.7.9 Application-specific password required. Learn more at\n5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor 20-20020a17090a035400b00264066aeb5fsm2298148pjf.36 - gsmtp')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neosoft/airflow/py_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1887, in handle_failure
    self.email_alert(error, task)
  File "/home/neosoft/airflow/py_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2297, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/neosoft/airflow/py_env/lib/python3.8/site-packages/airflow/utils/email.py", line 78, in send_email
    return backend(
  File "/home/neosoft/airflow/py_env/lib/python3.8/site-packages/airflow/utils/email.py", line 152, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/neosoft/airflow/py_env/lib/python3.8/site-packages/airflow/utils/email.py", line 279, in send_mime_email
    smtp_conn.login(smtp_user, smtp_password)
  File "/usr/lib/python3.8/smtplib.py", line 743, in login
    raise last_exception
  File "/usr/lib/python3.8/smtplib.py", line 732, in login
    (code, resp) = self.auth(
  File "/usr/lib/python3.8/smtplib.py", line 655, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (534, b'5.7.9 Application-specific password required. Learn more at\n5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor m26-20020a056a00165a00b0067738f65039sm443422pfc.83 - gsmtp')
[2023-07-20T12:52:54.632+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 417 for task run_spark (Bash command failed. The command returned a non-zero exit code 1.; 82053)
[2023-07-20T12:52:54.669+0530] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-20T12:52:54.695+0530] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
