[2023-07-21T18:49:31.821+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Data_processing.run_spark scheduled__2023-07-20T11:00:00+00:00 [queued]>
[2023-07-21T18:49:31.827+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Data_processing.run_spark scheduled__2023-07-20T11:00:00+00:00 [queued]>
[2023-07-21T18:49:31.827+0530] {taskinstance.py:1308} INFO - Starting attempt 2 of 4
[2023-07-21T18:49:31.851+0530] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_spark> on 2023-07-20 11:00:00+00:00
[2023-07-21T18:49:31.857+0530] {standard_task_runner.py:57} INFO - Started process 259892 to run task
[2023-07-21T18:49:31.861+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Data_processing', 'run_spark', 'scheduled__2023-07-20T11:00:00+00:00', '--job-id', '467', '--raw', '--subdir', 'DAGS_FOLDER/assignment2.py', '--cfg-path', '/tmp/tmpckiqf50d']
[2023-07-21T18:49:31.862+0530] {standard_task_runner.py:85} INFO - Job 467: Subtask run_spark
[2023-07-21T18:49:31.927+0530] {task_command.py:410} INFO - Running <TaskInstance: Data_processing.run_spark scheduled__2023-07-20T11:00:00+00:00 [running]> on host neosoft-Latitude-E5270
[2023-07-21T18:49:32.023+0530] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='nikitaneti21@gmail.com' AIRFLOW_CTX_DAG_OWNER='Nikita' AIRFLOW_CTX_DAG_ID='Data_processing' AIRFLOW_CTX_TASK_ID='run_spark' AIRFLOW_CTX_EXECUTION_DATE='2023-07-20T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-20T11:00:00+00:00'
[2023-07-21T18:49:32.027+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-21T18:49:32.027+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'spark_command']
[2023-07-21T18:49:32.038+0530] {subprocess.py:86} INFO - Output:
[2023-07-21T18:49:32.040+0530] {subprocess.py:93} INFO - /usr/bin/bash: spark_command: command not found
[2023-07-21T18:49:32.040+0530] {subprocess.py:97} INFO - Command exited with return code 127
[2023-07-21T18:49:32.054+0530] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/neosoft/airflow/py_env/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-07-21T18:49:32.059+0530] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=Data_processing, task_id=run_spark, execution_date=20230720T110000, start_date=20230721T131931, end_date=20230721T131932
[2023-07-21T18:49:32.075+0530] {base.py:73} INFO - Using connection ID 'smtp_default' for task execution.
[2023-07-21T18:49:32.075+0530] {email.py:268} INFO - Email alerting: attempt 1
[2023-07-21T18:49:33.776+0530] {email.py:280} INFO - Sent an alert email to ['nikitaneti21@gmail.com']
[2023-07-21T18:49:35.424+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 467 for task run_spark (Bash command failed. The command returned a non-zero exit code 127.; 259892)
[2023-07-21T18:49:35.451+0530] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-21T18:49:35.492+0530] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
